@startuml

!pragma teoz true
participant Action
box Component Pane
    box Entity Property #LightBlue
        participant Property
        participant ObservableEntity
        participant ObservableVersion
    end box
    participant KlComponentPane

end box
participant KlWidgetFactory
Action -> Property: setValue()
Property -> KlComponentPane : ObservableEntity Changed

activate KlComponentPane
KlComponentPane -> "Entity GridPane": clear layout
KlComponentPane -> ObservableEntity: getObservableFields()
ObservableEntity -> KlComponentPane: ImmutableMap<ComponentField,\n\t\t\t   ObservableField>
KlComponentPane -> LayoutProvider: computeLayout(\n\tImmutableList<ComponentFieldSpecification>)
LayoutProvider -> KlComponentPane: ImmutableMap<ComponentFieldSpecification,\n\t\t\t   GridLayoutForComponent>
loop for each component field specification
    KlComponentPane -> KlWidgetFactory: make KlWidget
    KlWidgetFactory -> KlComponentPane: KlWidget
    KlComponentPane -> "Entity GridPane": Add KlWidget to Layout with GridLayoutForComponent
    alt field is version list
        KlComponentPane -> KlComponentPane: contains detail pane for version element
        alt detail pane for version is present
            KlComponentPane -> ObservableVersion: getObservableFields()
            ObservableVersion -> KlComponentPane: ImmutableMap<ComponentField,\n\t\t\t   ObservableField>
            KlComponentPane -> LayoutProvider: computeLayout(\n\tImmutableList<ComponentFieldSpecification>)
            LayoutProvider -> KlComponentPane: ImmutableMap<ComponentFieldSpecification,\n\t\t\t   GridLayoutForComponent>
            KlComponentPane -> KlWidgetFactory: make KlWidget
            KlWidgetFactory -> KlComponentPane: KlWidget
            KlComponentPane -> "Version GridPane": Add KlWidget to Layout with GridLayoutForComponent
        end
    end
end
deactivate  KlComponentPane
@enduml