#ScenicView properties
#Thu Jul 17 16:42:09 PDT 2025
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=true
showSearchBar=true
splitPaneDividerPosition=0.4991339491916859
stageHeight=1285.0
stageWidth=1732.0
